function [scenario, egoVehicle] = parking_route()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 21-Sep-2025 10:52:22

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 40, ...
    'SampleTime', 0.1);

% Add all road segments
roadCenters = [74.55 0 0;
    -60 0 0];
marking = [laneMarking('Solid')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [0 67.3 0;
    0 -67.3 0];
marking = [laneMarking('Solid')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

roadCenters = [67.3 74.55 0;
    67.3 -74.55 0];
marking = [laneMarking('Solid')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road2');

roadCenters = [67.3 -67.3 0;
    -60 -67.3 0];
marking = [laneMarking('Solid')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road3');

roadCenters = [67.3 67.3 0;
    -60 67.3 0];
marking = [laneMarking('Solid')
    laneMarking('Dashed')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road4');

roadCenters = [30 -67.3 0;
    30 -55 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 6, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 4.7, ...
    'Position', [-57 -1.75 0], ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-57 -1.75 0;
    -40 -1.75 0;
    -29.9 -5.15 0;
    -10 -5.6 0;
    -5.3 -7.9 0;
    -5.2 -14.3 0;
    -3.4 -28.4 0;
    -1.9 -58 0;
    7.9 -69.4 0;
    13.9 -69.4 0;
    24.2 -69.4 0;
    31.3 -60.1 0;
    31.3 -56.8 0;
    33.3 -52.8 0;
    37.1 -52 0;
    57.7 -52.8 0];
speed = [9;9;3;8;2;6;8;8;3;8;8;3;2;2;2;2];
trajectory(egoVehicle, waypoints, speed, 'Yaw', yaw);

% Add the non-ego actors
vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 4.7, ...
    'Position', [-13.0383495799169 61.4902555927951 0], ...
    'Pitch', -0.00535372687209605, ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Wheelbase', 2.8, ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [183 70 255] / 255, ...
    'Name', 'Car');

